"""nuevo

Revision ID: 37820aa3ca8d
Revises: 
Create Date: 2025-01-20 15:06:50.792659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37820aa3ca8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('tel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
