"""changes

Revision ID: 3b8d27f3412c
Revises: 
Create Date: 2025-02-01 13:50:55.699301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8d27f3412c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_infoApi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=70), nullable=True),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contraseña', sa.String(length=500), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_telegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.Column('tel', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction__bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamA_id', sa.Integer(), nullable=False),
    sa.Column('teamB_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('tiros', sa.Integer(), nullable=False),
    sa.Column('es_local_A', sa.Boolean(), nullable=False),
    sa.Column('goles_A', sa.Integer(), nullable=False),
    sa.Column('goles_B', sa.Integer(), nullable=False),
    sa.Column('corners', sa.Integer(), nullable=False),
    sa.Column('posesion', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Integer(), nullable=False),
    sa.Column('clima', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['teamA_id'], ['team_prediction.id'], ),
    sa.ForeignKeyConstraint(['teamB_id'], ['team_prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction__bot')
    op.drop_table('user_telegram')
    op.drop_table('user')
    op.drop_table('team_prediction')
    # ### end Alembic commands ###
