"""fix

Revision ID: 56219e74fec1
Revises: 5acfad9532da
Create Date: 2025-02-02 13:53:58.711730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56219e74fec1'
down_revision = '5acfad9532da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_telegram', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('userId',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_telegram', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
