"""timeZone in user date

Revision ID: 9b49b4f54a88
Revises: ae78fc7a733a
Create Date: 2025-02-03 16:12:55.688363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b49b4f54a88'
down_revision = 'ae78fc7a733a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeZone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timeZone')

    # ### end Alembic commands ###
