"""changes

Revision ID: e13ccefcd8c9
Revises: 3b8d27f3412c
Create Date: 2025-02-02 13:39:27.249978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e13ccefcd8c9'
down_revision = '3b8d27f3412c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('user_telegram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('suscribed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chat_id', sa.Integer(), nullable=False))
        batch_op.drop_column('tel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_telegram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('chat_id')
        batch_op.drop_column('suscribed')
        batch_op.drop_column('userId')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
